routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//URL::forceScheme('https');

Auth::routes([
    'register' => true,
    'verify' => false,
    'reset' => true
]);

/**
 * Dashboard routes
 */
Route::prefix(config('anita.dashboard.prefix'))
    ->middleware('auth')
    ->middleware('administration')
    ->name('admin.')
    ->group(function() {
        /* Dashboard */
        Route::get('/', [config('anita.dashboard.home.class'), config('anita.dashboard.home.method')])->name('home');

        /* Editor settings */
        Route::name('editor.')
            ->prefix('editor')
            ->group(function() {
                Route::get('templates', [\App\Http\Controllers\Administrator\Editor\Templates::class, 'index'])->name('templates');
            });

        /* Страницы */
        Route::prefix('page')
            ->name('page.')
            ->group(function() {
                Route::get('/{uuid?}', [App\Http\Controllers\Administrator\Page\Index::class, 'index'])->name('home');
                Route::get('/edit/{locale}/{uuid?}', [App\Http\Controllers\Administrator\Page\Edit::class, 'index'])->name('edit');
                Route::post('/store', [App\Http\Controllers\Administrator\Page\Store::class, 'index'])->name('save');
                Route::post('/delete', [App\Http\Controllers\Administrator\Page\Delete::class, 'index'])->name('delete');
                Route::post('/sortable', [App\Http\Controllers\Administrator\Page\Sortable::class, 'index'])->name('sortable');
            });

        /* Навигация */
        Route::prefix('navigation')
            ->name('navigation.')
            ->group(function() {
                Route::get('/', [App\Http\Controllers\Administrator\Navigation\Index::class, 'index'])->name('home');
                Route::get('/edit/{uuid?}', [\App\Http\Controllers\Administrator\Navigation\Edit::class, 'index'])->name('edit');
                Route::post('/store', [\App\Http\Controllers\Administrator\Navigation\Store::class, 'index'])->name('store');
                Route::post('/delete', [\App\Http\Controllers\Administrator\Navigation\Delete::class, 'index'])->name('delete');

                /* Ссылки в навигации */
                Route::prefix('items')
                    ->name('items.')
                    ->group(function() {
                        Route::get('/{uuid}', [\App\Http\Controllers\Administrator\Navigation\Items\Index::class, 'index'])->name('home');
                        Route::get('/{uuid}/edit/{locale?}/{navigation_item:uuid?}', [\App\Http\Controllers\Administrator\Navigation\Items\Edit::class, 'index'])->name('edit');
                        Route::post('/store', [\App\Http\Controllers\Administrator\Navigation\Items\Store::class, 'index'])->name('store');
                        Route::post('/delete', [\App\Http\Controllers\Administrator\Navigation\Items\Delete::class, 'index'])->name('delete');
                        Route::post('/sortable', [\App\Http\Controllers\Administrator\Navigation\Items\Sortable::class, 'index'])->name('sortable');
                        Route::post('/ajax/objects-type', [\App\Http\Controllers\Administrator\Navigation\Items\ObjectsType::class, 'index'])->name('objects');
                    });
            });

        /* Finder */
        Route::prefix('finder')
            ->name('finder.')
            ->group(function() {
                Route::get('/{uuid?}', [\App\Http\Controllers\Administrator\Finder\Editor::class, 'index'])->name('home');
                Route::get('/file/edit/{locale}/{uuid}', [\App\Http\Controllers\Administrator\Finder\FileEdit::class, 'index'])->name('file.edit');
                Route::post('/upload/editor', [\App\Http\Controllers\Administrator\Finder\EditorUpload::class, 'index'])->name('editor.upload');
                Route::post('/upload', [\App\Http\Controllers\Administrator\Finder\Upload::class, 'index'])->name('upload');
                Route::post('/delete', [\App\Http\Controllers\Administrator\Finder\Delete::class, 'index'])->name('delete');
                Route::post('/sortable/{uuid?}', [\App\Http\Controllers\Administrator\Finder\Sortable::class, 'index'])->name('sortable');
                Route::post('/sortable/folder/{uuid?}', [\App\Http\Controllers\Administrator\Finder\Sortable::class, 'folder'])->name('sortable.folder');
                Route::post('/store', [\App\Http\Controllers\Administrator\Finder\FileStore::class, 'index'])->name('file.store');

                Route::prefix('folder')
                    ->name('folder.')
                    ->group(function() {
                        Route::get('/create/{uuid}', [\App\Http\Controllers\Administrator\Finder\Folder\Create::class, 'index'])->name('create');
                        Route::post('/create', [\App\Http\Controllers\Administrator\Finder\Folder\Store::class, 'index'])->name('store');
                    });
        });

        /* Каталог */
        Route::prefix('catalog')
            ->name('catalog.')
            ->group(function() {
                Route::get('/', [\App\Http\Controllers\Administrator\Catalog\Index::class, 'index'])->name('home');

                /* категории */
                Route::prefix('category')
                    ->name('category.')
                    ->group(function() {
                        Route::get('/{uuid?}', [\App\Http\Controllers\Administrator\Catalog\Category\Index::class, 'index'])->name('home');
                        Route::get('edit/{locale}/{uuid?}', [\App\Http\Controllers\Administrator\Catalog\Category\Edit::class, 'index'])->name('edit');
                        Route::get('/categories', [\App\Http\Controllers\Administrator\Catalog\Category\Modal::class, 'index'])->name('categories');
                        Route::post('/store', [\App\Http\Controllers\Administrator\Catalog\Category\Store::class, 'index'])->name('store');
                        Route::post('/delete', [\App\Http\Controllers\Administrator\Catalog\Category\Delete::class, 'index'])->name('delete');
                        Route::post('/sortable', [\App\Http\Controllers\Administrator\Catalog\Category\Sortable::class, 'index'])->name('sortable');
                    });

                /* Характеристики */
                Route::prefix('feature')
                    ->name('feature.')
                    ->group(function() {
                        Route::get('/', [\App\Http\Controllers\Administrator\Catalog\Feature\Index::class, 'index'])->name('home');
                        Route::get('/edit/{locale}/{uuid?}', [\App\Http\Controllers\Administrator\Catalog\Feature\Edit::class, 'index'])->name('edit');
                        Route::get('/page/edit/{locale}/{uuid?}', [\App\Http\Controllers\Administrator\Catalog\Feature\Page::class, 'index'])->name('page.edit');
                        Route::post('/page/store', [\App\Http\Controllers\Administrator\Catalog\Feature\PageStore::class, 'index'])->name('page.store');
                        Route::post('/params/view_product', [\App\Http\Controllers\Administrator\Catalog\Feature\ViewOptions::class, 'product'])->name('json.product');
                        Route::post('/params/view_filter', [\App\Http\Controllers\Administrator\Catalog\Feature\ViewOptions::class, 'filter'])->name('json.filter');
                        Route::post('/store', [\App\Http\Controllers\Administrator\Catalog\Feature\Store::class, 'index'])->name('store');
                        Route::post('/delete', [\App\Http\Controllers\Administrator\Catalog\Feature\Delete::class, 'index'])->name('delete');
                        Route::post('/sortable', [\App\Http\Controllers\Administrator\Catalog\Feature\Sortable::class, 'index'])->name('sortable');
                        Route::post('/sortable/variants', [\App\Http\Controllers\Administrator\Catalog\Feature\Sortable::class, 'variants'])->name('sortable.variants');
                    });

                /* Группы характеристик */
                Route::prefix('feature-group')
                    ->name('feature.group.')
                    ->group(function() {
                        Route::get('/', [\App\Http\Controllers\Administrator\Catalog\FeatureGroup\Index::class, 'index'])->name('home');
                        Route::get('/edit/{locale}/{uuid?}', [\App\Http\Controllers\Administrator\Catalog\FeatureGroup\Edit::class, 'index'])->name('edit');
                        Route::post('/store', [\App\Http\Controllers\Administrator\Catalog\FeatureGroup\Store::class, 'index'])->name('store');
                        Route::post('/delete', [\App\Http\Controllers\Administrator\Catalog\FeatureGroup\Delete::class, 'index'])->name('delete');
                        Route::post('/sortable', [\App\Http\Controllers\Administrator\Catalog\FeatureGroup\Sortable::class, 'index'])->name('sortable');
                    });

                /* Товары */
                Route::prefix('product')
                    ->name('product.')
                    ->group(function() {
                        Route::get('/', [\App\Http\Controllers\Administrator\Catalog\Product\Index::class, 'index'])->name('home');
                        Route::get('/edit/{locale}/{uuid?}', [\App\Http\Controllers\Administrator\Catalog\Product\Edit::class, 'index'])->name('edit');
                        Route::post('/copy', [\App\Http\Controllers\Administrator\Catalog\Product\Copy::class, 'index'])->name('copy');
                        Route::post('/store', [\App\Http\Controllers\Administrator\Catalog\Product\Store::class, 'index'])->name('store');

resources/views/administrator/content/nested-rows/default.blade.php
<li class="list-item" data-uuid="{{ $item->uuid }}">
    {{-- Объект для сортировки записей --}}
    @isset($routes['sortable'])
        <a href="javascript:void(0);" data-drag="true" title="{{ __('nested.action') }}">
            <i class="fas fa-sort"></i>
        </a>
    @endif

    {{-- Иконка элемента --}}
    <div class="item-icon">
        @if ($item->isLeaf())
            <picture>
                <source type="image/webp" srcset="{{ asset('administrator/icons/file.webp') }}">
                <img src="{{ asset('administrator/icons/file.png') }}" alt="">
            </picture>
        @else
            <picture>
                <source type="image/webp" srcset="{{ asset('administrator/icons/folder.webp') }}">
                <img src="{{ asset('administrator/icons/folder.png') }}" alt="">
            </picture>
        @endif
    </div>

    {{-- Основные данные по элементу --}}
    <div class="flex-fill ps-1">
        @if (isset($item->meta->is_active))
            <small class="badge-dot {{ $item->meta->is_active ? 'bg-success' : 'bg-danger' }}" title="{{ $item->meta->is_active ? __('global.active') : __('global.unactive') }}"></small>
        @endif
        <span class="link-edit">
            @if ($item->isLeaf())
                <a href="{{ route($routes['edit'], ['uuid' => $item->uuid, 'locale' => app()->getLocale()]) }}">{{ $item->name }}</a>
                <small><i class="fas fa-pencil-alt ms-1"></i></small>
            @else
                <a href="{{ route($routes['home'], ['uuid' => $item->uuid]) }}">{{ $item->name }}</a>
                <small><i class="fas fa-long-arrow-alt-right ms-1"></i></small>
            @endif
        </span>

        <br>
        <ul class="list-inline">
            @if (count(config('translatable.locales')) > 1)
            <li class="list-inline-item">
                @include('administrator.resources.translation-item-variants', ['object' => $item])
            </li>
            @endif

            <li class="list-inline-item">
                <strong>
                    <small>{{ __('meta.columns.link') }}:</small>
                </strong>
                <a href="{{ route('view', $item->meta->url) }}" target="_blank" class="text-secondary">
                    <small>
                        /{{ \Illuminate\Support\Str::limit($item->meta->url, 30) }}
                    </small>
                </a>
            </li>

            <li class="list-inline-item">
                <strong>
                    <small>Robots:</small>
                </strong>
                @foreach(explode(', ', $item->meta->robots) as $val)
                    <span class="badge bg-light @if(in_array($val, ['all', 'index', 'follow']))text-success @else text-danger @endif">{{ $val }}</span>
                @endforeach
            </li>
        </ul>
    </div>

    {{-- Meta теги --}}
    @if ($item->isLeaf() && isset($item->meta))

    @else
        @isset ($trans_choice)
            <small class="text-secondary">
                {{ $children_objects_count }}
                {{ trans_choice($trans_choice, $children_objects_count) }}
            </small>
        @endif
    @endif

    @if (isset($item->meta->publish_at))
        {{-- Время публикации --}}
        <span class="col-md-2 text-nowrap">
            <small class="text-secondary">{{ __('page.columns.publish_at') }}:</small><br>
            <small>{{ $item->meta->publish_at }}</small>
        </span>
    @else
        {{-- Время создания --}}
        <span class="col-md-2 text-nowrap px-2">
            <small class="text-secondary">{{ __('page.columns.date_create') }}:</small><br>
            <small>{{ $item->created_at }}</small>
        </span>
    @endif

    <span class="d-flex col-md-1 justify-content-end">
        <a href="{{ route($routes['edit'], ['uuid' => $item->uuid, 'locale' => app()->getLocale()]) }}" class="btn btn-sm text-secondary">
            <i class="fas fa-pencil-alt"></i>
        </a>

        {{-- Удаление --}}
        @include('administrator.resources.delete-form', ['route_delete' => route($routes['delete'])])
    </span>
</li>

resources/views/administrator/content/nested-rows/features.blade.php
<li class="list-item" data-uuid="{{ $item->uuid }}">
    {{-- Объект для сортировки записей --}}
    @isset($routes['sortable'])
        <a href="javascript:void(0);" data-drag="true" title="{{ __('nested.action') }}">
            <i class="fas fa-sort"></i>
        </a>
    @endif

    {{-- Иконка элемента --}}
    <div class="item-icon">
        @if ($children_objects_count = $item->children->get()->toFlatTree()->count())
            <img src="{{ asset('administrator/icons/folder.png') }}" alt="">
        @else
            <img src="{{ asset('administrator/icons/file.png') }}" alt="">
        @endif
    </div>

    {{-- Основные данные по элементу --}}
    <div class="flex-fill ps-1">
        <span class="link-edit">
            @if ($children_objects_count)
                <a href="{{ route($routes['home'], ['uuid' => $item->uuid]) }}">{{ $item->name }}</a>
                <i class="fas fa-long-arrow-alt-right"></i>
            @else
                <a href="{{ route($routes['edit'], ['uuid' => $item->uuid, 'locale' => $item->translate()->locale]) }}">{{ $item->name }}</a>
                <i class="fas fa-pencil-alt"></i>
            @endif
        </span>

        <br>
        <small class="text-secondary">
            <i class="fas fa-crosshairs text-primary"></i>
            {{ $item->getPurposeTitle() }}
        </small>
    </div>


    {{-- Категории --}}
    <div class="w-25">
        <small class="text-secondary">{{ __('catalog.feature.categories') }}</small>
        <p>
            <small>
                @if ($item->categories && $item->categories->count())
{{--                    @dump($item->categories)--}}
                    @php($limit = 3)
                    @foreach ($item->categories as $index => $c)
                        @if($index < $limit)
                        {{ $c->category->name }}@if($index + 1 != $item->categories->count() && $index < $limit - 1), @endif
                        @endif
                    @endforeach

                    @if ($item->categories->count() > $limit)
                        &hellip;
                        {{ __('catalog.feature.and_more_categories', ['count' => $item->categories->count() - $limit]) }}
                        {{ trans_choice('catalog.feature.choice_category', $item->categories->count() - $limit) }}
                    @endif
                @else
                    {{ $item->category ?? __('catalog.category.all') }}
                @endif
            </small>
        </p>
    </div>

    {{-- Группа характеристик --}}
    <div>
        <small class="text-secondary">Группа характеристик</small>
        <p>
            <small>
                {{ $item->feature_group_uuid ? $item->group->name : __('catalog.feature.group.no_group') }}
            </small>
        </p>
    </div>


    {{-- Время создания --}}
    <span>
        <small class="text-secondary">{{ __('page.columns.date_create') }}:</small><br>
        {{ $item->created_at }}
    </span>

    {{-- Удаление --}}
    @if($children_objects_count)
        @php($message_delete = __('page.delete_category_confirm', ['name' => $item->name]))
    @else
        @php($message_delete = __('page.delete_confirm', ['name' => $item->name]))
    @endif

    <form action="{{ route($routes['delete']) }}" method="post" onsubmit="return confirm('{{ $message_delete }}')">
        @csrf
        <button name="uuid" value="{{ $item->uuid }}" class="btn btn-link text-danger">
            <i class="fas fa-trash-alt"></i>
        </button>
    </form>
</li>

resources/views/administrator/content/nested-rows/navigation-item.blade.php
<li class="list-item"@if (empty($parent_uuid))data-uuid="{{ $node->uuid }}" @endif>
    @if (empty($parent_uuid))
        <a href="javascript:void(0);" data-drag="true" title="{{ __('nested.action') }}">
            <i class="fas fa-sort"></i>
        </a>
    @endif

    <div class="item-icon">
        @if ($count = $node->children->count())
            <img src="{{ asset('administrator/icons/folder.png') }}" alt="">
        @else
            <img src="{{ asset('administrator/icons/link.png') }}" alt="">
        @endif
    </div>

    <div class="flex-fill ps-1">
        <span class="link-edit">
        @if ($count && empty($parent_uuid))
            <a href="{{ route('admin.navigation.items.home', ['navigation_uuid' => $node->navigation->uuid, 'parent_id' => $node->uuid]) }}">{{ $node->name }}</a>
            <i class="fas fa-long-arrow-alt-right"></i>
        @else
            <a href="{{ route('admin.navigation.items.edit', ['navigation_uuid' => $node->navigation->uuid, 'uuid' => $node->uuid]) }}">{{ $node->name }}</a>
            <i class="fas fa-pencil-alt"></i>
        @endif
        </span>

        <br>
        <ul class="list-inline">
            <li class="list-inline-item">
                @if($node->is_active)
                    <small class="text-success">{{ __('navigation.items.is_active')[$node->is_active] }}</small>
                @else
                    <small class="text-danger">{{ __('navigation.items.is_active')[$node->is_active] }}</small>
                @endif
            </li>
            @if ($count)
                <li class="list-inline-item">
                    <small class="text-secondary">
                        {{ $count }}
                        {{ trans_choice('navigation.choice.pages', $count, []) }}
                    </small>
                </li>
            @endif
        </ul>
    </div>

    {{-- Meta теги --}}
    <div class="text-end">

    </div>

    {{-- Время публикации --}}
    <span>
        <small class="text-secondary">{{ __('navigation.columns.updated_at') }}:</small><br>
        {{ $item->updated_at }}
    </span>

    {{-- Время создания страницы --}}
    <span>
        <small class="text-secondary">{{ __('navigation.columns.created_at') }}:</small><br>
        {{ $item->created_at }}
    </span>

    {{-- Удаление --}}
    <div class="d-flex col-md-1 flex-nowrap">
        <a href="{{ route('admin.navigation.items.edit', ['navigation_uuid' => $node->navigation->uuid, 'uuid' => $node->uuid]) }}" class="btn btn-sm text-secondary">
            <i class="fas fa-pencil-alt"></i>
        </a>
        @include('administrator.resources.delete-form', ['route_delete' => route('admin.navigation.items.delete')])
    </div>
</li>

resources/views/administrator/content/nested-rows/navigation.blade.php
<li class="list-item" data-uuid="{{ $item->uuid }}">
    {{-- Объект для сортировки записей --}}
    @isset($routes['sortable'])
        <a href="javascript:void(0);" data-drag="true" title="{{ __('nested.action') }}">
            <i class="fas fa-sort"></i>
        </a>
    @endif

    {{-- Иконка элемента --}}
    <div class="item-icon">
        <picture>
            <source type="image/webp" srcset="{{ asset('administrator/icons/navigation.webp') }}">
            <img src="{{ asset('administrator/icons/navigation.png') }}" alt="">
        </picture>
    </div>

    {{-- Основные данные по элементу --}}
    <div class="flex-fill ps-1">
        <span class="link-edit">
            <a href="{{ route('admin.navigation.items.home', ['uuid' => $item->uuid]) }}">
                {{ $item->name }}</a>
            <i class="fas fa-long-arrow-alt-right"></i>
        </span>

        <br>
        {{-- Дополнительная информация по меню: ключ, комментарий --}}
        <ul class="list-inline">
            {{-- ключ доступа к меню --}}
            <li class="list-inline-item">
                <small class="text-success" title="{{ __('navigation.columns.key') }}">
                    <i class="fas fa-key"></i>
                    &lt;x-navigation key="{{ $item->key }}"&gt;
                </small>
            </li>

            {{-- комментарий --}}
            @if ($item->description)
                <li class="list-inline-item">
                    <small class="text-secondary">
                        <i class="far fa-comment"></i>
                        {{ \Illuminate\Support\Str::limit($item->description, 50) }}
                    </small>
                </li>
            @endif
        </ul>
    </div>

    {{-- Время создания --}}
    <span class="col-md-2 text-nowrap">
        <small class="text-secondary">{{ __('page.columns.date_create') }}:</small><br>
        <small>{{ $item->created_at }}</small>
    </span>

    {{-- Удаление --}}
    <div class="d-flex col-md-1 flex-nowrap">
        <a href="{{ route('admin.navigation.items.home', ['uuid' => $item->uuid]) }}" class="btn btn-sm text-secondary">
            <i class="fas fa-pencil-alt"></i>
        </a>
        @include('administrator.resources.delete-form', ['route_delete' => route('admin.navigation.delete')])
    </div>
</li>

resources/views/administrator/content/nested-rows/product.blade.php
<li class="list-item" data-uuid="{{ $item->uuid }}">
    {{-- Объект для сортировки записей --}}
    @isset($routes['sortable'])
        <a href="javascript:void(0);" data-drag="true" title="{{ __('nested.action') }}">
            <i class="fas fa-sort"></i>
        </a>
    @endif

    {{-- Иконка элемента --}}
    @if (isset($item->images) && $item->images->count())
    <a
        href="{{ \Illuminate\Support\Facades\Storage::url($item->images->first()->fullName()) }}"
        data-type="image"
        class="item-icon"
        style="width: 50px;"
        title="{{ $item->name }} {{ $item->images->first()->name }}"
    >
        <img src="{{ \Illuminate\Support\Facades\Storage::url($item->images->first()->thumbnail()) }}" class="rounded" alt="">
    </a>
    @endif

    {{-- Основные данные по элементу --}}
    <div class="flex-fill ps-1">
        <span class="link-edit">
            <a href="{{ route($routes['edit'], ['uuid' => $item->uuid, 'locale' => $item->translate()->locale]) }}">{{ $item->name }}</a>
            <i class="fas fa-pencil-alt"></i>
        </span>

        <br>
        <small class="text-secondary">{{ $item->categories->pluck('name')->join(', ') }}</small>
    </div>

    {{-- Meta теги --}}
    @if (isset($item->meta))
        <div class="text-end" title="{{ __('meta.descriptions.robots') }}">
            @foreach(explode(', ', $item->meta->robots) as $val)
                <span class="badge bg-light @if(in_array($val, ['all', 'index', 'follow']))text-success @else text-danger @endif">{{ $val }}</span>
            @endforeach

            @if ($item->meta->title)
                <br><i class="fas fa-chart-line text-success ms-1"></i>
                <small class="text-secondary" title="{{ __('meta.columns.title') }}">
                    {{ \Illuminate\Support\Str::limit($item->meta->title, 30) }}
                </small>
            @endif
        </div>
    @else
        @isset ($trans_choice)
            <small class="text-secondary">
                {{ $children_objects_count }}
                {{ trans_choice($trans_choice, $children_objects_count) }}
            </small>
        @endif
    @endif

    {{-- Время создания --}}
    <span>
        <small class="text-secondary">{{ __('page.columns.date_create') }}:</small><br>
        {{ $item->created_at }}
    </span>

    {{-- Действия --}}
    <div class="d-flex flex-nowrap">
        {{-- Сделает копию товара --}}
        <form action="{{ route('admin.catalog.product.copy') }}" method="post">
            @csrf
            <button name="uuid" value="{{ $item->uuid }}" class="btn btn-link text-secondary">
                <i class="far fa-copy"></i>
            </button>
        </form>

        {{-- Удалит товар --}}
        <form action="{{ route($routes['delete']) }}" method="post" onsubmit="return confirm('{{ __('page.delete_confirm', ['name' => $item->name]) }}')">
            @csrf
            <button name="uuid" value="{{ $item->uuid }}" class="btn btn-link text-danger">
                <i class="fas fa-trash-alt"></i>
            </button>
        </form>
    </div>
</li>

resources/views/administrator/content/nested-rows/users.blade.php
<li class="list-item" data-uuid="{{ $item->uuid }}">
    {{-- Объект для сортировки записей --}}
    @isset($routes['sortable'])
        <a href="javascript:void(0);" data-drag="true" title="{{ __('nested.action') }}">
            <i class="fas fa-sort"></i>
        </a>
    @endif

    {{-- Аватар --}}
    <div class="item-icon" style="width: 50px;">
        <a
            class="item-icon"
            @if (isset($item->avatar))
            href="{{ \Illuminate\Support\Facades\Storage::url($item->avatar->fullName()) }}"
            data-type="image"
            @endif
            style="width: 50px;"
        >
            <img src="{{ $item->getAvatarUrl() }}" class="rounded" alt="">
        </a>
    </div>

    {{-- Основные данные по элементу --}}
    <div class="flex-fill ps-1">
        <span class="link-edit">
            <a href="{{ route($routes['edit'], ['id' => $item->id, 'locale' => app()->getLocale()]) }}">{{ $item->name }}</a>
            <i class="fas fa-pencil-alt"></i>
        </span>

        <br>
        <span class="text-secondary">
            {{ $item->email }}
        </span>
    </div>

    <div class="col-md-2">
        {{ __('user.columns.role') }}:<br>
        @if ($item->isAdmin())
            <span class="text-success">{{ __('user.roles')[$item->role] }}</span>
        @else
            <span class="text-secondary">{{ __('user.roles')[$item->role] }}</span>
        @endif
    </div>

    {{-- Время создания --}}
    <span class="col-md-2">
        <small class="text-secondary">{{ __('user.columns.created_at') }}:</small><br>
        {{ $item->created_at }}
    </span>

    {{-- Удаление --}}
    <div class="col-md-1">
        @if (\Illuminate\Support\Facades\Auth::user()->created_at < $item->created_at)
        <form action="{{ route($routes['delete']) }}" method="post" onsubmit="return confirm('{{ __('page.delete_confirm', ['name' => $item->name]) }}')">
            @csrf
            <button name="id" value="{{ $item->id }}" class="btn btn-link text-danger">
                <i class="fas fa-trash-alt"></i>
            </button>
        </form>
        @endif
    </div>
</li>